* File: netlist.sp.TEST_INV3.pxi
* Created: Wed Jun 11 15:46:59 2025
* 
x_PM_TEST_INV3%VSS N_VSS_MM0_s N_VSS_MM0_b VSS VSS PM_TEST_INV3%VSS
x_PM_TEST_INV3%VDD N_VDD_MM1_s N_VDD_MM1_b VDD VDD PM_TEST_INV3%VDD
x_PM_TEST_INV3%A N_A_MM0_g N_A_MM1_g A PM_TEST_INV3%A
x_PM_TEST_INV3%Y N_Y_MM0_d N_Y_MM1_d Y PM_TEST_INV3%Y
